"""resume_version status and error

Revision ID: 6dc8524982a9
Revises: 82f81acdbc8b
Create Date: 2026-09-01 13:38:28.724825

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dc8524982a9"
down_revision: str | Sequence[str] | None = "82f81acdbc8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resume_versions",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "extracting",
                "structuring",
                "ready",
                "failed",
                name="resume_version_status",
                native_enum=False,
            ),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column("resume_versions", sa.Column("error", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # server_default was only to backfill existing rows; the app sets status.
    op.alter_column("resume_versions", "status", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resume_versions", "error")
    op.drop_column("resume_versions", "status")
    # ### end Alembic commands ###
