"""drop users.password_hash (passwordless auth)

Revision ID: 82f81acdbc8b
Revises: 6e90a7ec4ec1
Create Date: 2026-08-31 15:33:44.129041

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82f81acdbc8b"
down_revision: str | Sequence[str] | None = "6e90a7ec4ec1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_hash", sa.TEXT(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###
